# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhomGubThank(object):
    def setupUi(self, PhomGubThank):
        PhomGubThank.setObjectName("PhomGubThank")
        PhomGubThank.resize(751, 392)
        self.centralwidget = QtWidgets.QWidget(PhomGubThank)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-30, 0, 781, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(210, 30, 111, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(30, 0, 751, 391))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"\n"
"\n"
";\n"
"    background-color: rgb(238, 255, 103);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(290, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(260, 10, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(630, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.pushButton.setFont(font)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(230, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 220, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(330, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(90, 280, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(290, 140, 71, 31))
        self.spinBox.setMaximum(100)
        self.spinBox.setMinimum(1)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 330, 101, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    color: rgb(252, 63, 53);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(560, 300, 131, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(170, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_4.setGeometry(QtCore.QRect(420, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_5.setGeometry(QtCore.QRect(330, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(580, 250, 91, 16))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(500, 90, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(590, 90, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setGeometry(QtCore.QRect(30, 0, 751, 381))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(144, 255, 107);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(180, 10, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 340, 91, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    \n"
"    color: rgb(15, 0, 144);\n"
"\n"
"}")
        self.pushButton_6.setIconSize(QtCore.QSize(30, 26))
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(120, 320, 81, 41))
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(210, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{  \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(110, 130, 561, 151))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"background-color: rgb(28, 179, 74);\n"
"\n"
"}")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(340, 320, 131, 41))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(490, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{  \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(110, 100, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_14.raise_()
        self.pushButton_5.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.label_11.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setGeometry(QtCore.QRect(20, 0, 761, 381))
        self.frame_4.setMinimumSize(QtCore.QSize(761, 381))
        self.frame_4.setMaximumSize(QtCore.QSize(761, 381))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(141, 255, 228);\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 260, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(170, 80, 441, 151))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(48)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_2 = QtWidgets.QFrame(self.page_3)
        self.frame_2.setGeometry(QtCore.QRect(30, -10, 751, 411))
        self.frame_2.setMinimumSize(QtCore.QSize(751, 411))
        self.frame_2.setMaximumSize(QtCore.QSize(751, 411))
        self.frame_2.setStyleSheet("QFrame{\n"
"    \n"
"    \n"
"    background-color: rgb(169, 165, 201);\n"
" \n"
"    border-color: rgb(17, 38, 255);\n"
"    boarder-radius:20px;\n"
"\n"
"\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(180, 100, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(400, 140, 331, 31))
        self.label_12.setMinimumSize(QtCore.QSize(331, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 210, 171, 81))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_3)
        PhomGubThank.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(PhomGubThank)
        self.toolBar.setObjectName("toolBar")
        PhomGubThank.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(PhomGubThank)
        self.stackedWidget.setCurrentIndex(3)
        self.pushButton_2.clicked.connect(self.textEdit.clear)
        self.pushButton_2.clicked.connect(self.spinBox.clear)
        self.pushButton_2.clicked.connect(self.textEdit_4.clear)
        self.pushButton_2.clicked.connect(self.textEdit_3.clear)
        self.pushButton_2.clicked.connect(self.textEdit_5.clear)
        QtCore.QMetaObject.connectSlotsByName(PhomGubThank)
###push button

        self.pushButton_7.clicked.connect(self.gopage2)
        self.pushButton_8.clicked.connect(self.calculate)
        self.pushButton.clicked.connect(self.gopage3)
        self.pushButton_5.clicked.connect(self.gopage4)
        self.pushButton_3.clicked.connect(self.closewindow)
        self.pushButton_6.clicked.connect(self.backtopage2)
        
##personal info page
            
    def gopage2(self):
        self.stackedWidget.setCurrentIndex(0)

    def calculate(self):
        
        dicM= {"1-15":{"RUNNING":"RUNNING :500 calories in 30 minutes", "CYCLING":"CYCLING:260 calories in 10 minutes",
                       "DANCING":"DANCING:225 calories in 30 minutes","BODYWEIGHT":"BODYWEIGHT:112 calories in 30 minutes"
                       ,"COOKING":"COOKING:90 calories in 30 minutes"},
               "16-40":{"RUNNING":"RUNNING :450 calories in 30 minutes", "CYCLING":"CYCLING:250 calories in 10 minutes",
                       "DANCING":"DANCING:200 calories in 30 minutes","BODYWEIGHT":"BODYWEIGHT:150 calories in 30 minutes"
                       ,"GOLF":"GOLF:330 calories in 60 minutes"},
               "40+":{"RUNNING":"RUNNING:450 calories in 30 minutes", "CYCLING":"CYCLING:250 calories in 10 minutes",
                       "SWIMMING":"SWIMMING:510 calories in 60 minutes","JOGGING":"JOGGING:120 calories in 30 minutes"
                       ,"GOLF":"GOLF:330 calories in 60 minutes"}}

        dicMCAL={"1-15":{"RUNNING":500 , "CYCLING":260,"DANCING":225 ,"BODYWEIGHT":112 ,"COOKING":90  },
               "16-40":{"RUNNING ":450 , "CYCLING":250 ,"DANCING":200,"BODYWEIGHT":150 ,"GOLF":330  },
               "40+":{"RUNNING":450 , "CYCLING":250 ,"SWIMMING":510 ,"JOGGING":120,"GOLF":330 }}


       

        
        dicF={"1-15":{"RUNNING":"RUNNING :450 calories in 30 minutes", "CYCLING":"CYCLING:260 calories in 10 minutes",
                       "DANCING":"DANCING:250 calories in 30 minutes","BODYWEIGHT":"BODYWEIGHT:100 calories in 30 minutes"
                       ,"COOKING":"COOKING:90 calories in 30 minutes"}
              ,"16-40":{"RUNNING":"RUNNING :450 calories in 30 minutes", "CYCLING":"CYCLING:240 calories in 10 minutes",
                       "DANCING":"DANCING:200 calories in 30 minutes","BODYWEIGHT":"BODYWEIGHT:150 calories in 30 minutes"
                       ,"GOLF":"GOLF:320 calories in 60 minutes"},
              "40+":{"RUNNING":"RUNNING:450 calories in 30 minutes", "CYCLING":"CYCLING:250 calories in 10 minutes",
                       "SWIMMING":"SWIMMING:410 calories in 60 minutes","JOGGING":"JOGGING:110 calories in 30 minutes"
                       ,"GOLF":"GOLF:330 calories in 60 minutes"}}


        
        dicFCAL={"1-15":{"RUNNING":450 , "CYCLING":260 ,"DANCING":250 ,"BODYWEIGHT":100 ,"COOKING":90 }
              ,"16-40":{"RUNNING":450 , "CYCLING":240 , "DANCING":200 ,"BODYWEIGHT":150,"GOLF":320},
                 "40+":{"RUNNING":450 , "CYCLING":250, "SWIMMING":410,"JOGGING":110 ,"GOLF":330  }}
        

       

        

        ###BMI
        
        weight=self.textEdit_3.toPlainText()
        height=self.textEdit_4.toPlainText()
        weight=float(weight)
        height=float(height)
        if weight>0 and height >0:
            BMI = round(weight/height**2,2)    
            self.label_15.setText(str(BMI))
        else:
            None
      
        
       ##gender
        
        if self.radioButton.isChecked():
            gender = "male"
        elif self.radioButton_2.isChecked():
            gender = "female"
        
        
        age = self.spinBox.value()
        age = int(age)
        
      ##  if gender == "male":
       #     print("yyyy")
         #   if 1<=age and age<=15:
         #       a=dicM["1-15"]
         #   elif 15<age and age<=40:
           #     a=dicM["16-40"]
            #else:
             #   a=dicM["40+"]
     #   elif gender == "female":
       #     if 1<=age and age<=15:
         #       a=dicF["1-15"]
          #  elif 15<age and age<=40:
          #      a= dicF["16-40"]
           # else:
           #     a=dicF["40+"]
        
        
###cal goal for male
        if gender == "male":
            x = self.textEdit_5.toPlainText()
            x = int(x)
            total_cal = 0
            if age > 1 and age <= 15:
                for Mk1,Mv1 in dicMCAL.get("1-15").items():
                    if total_cal < x:
                        total_cal += Mv1
                if x > total_cal:
                    total_cal = x
            elif age > 15 and age <= 40:
                for Mk2,Mv2 in dicMCAL.get("16-40").items():
                    if total_cal <= x:
                        total_cal += Mv2
                if x > total_cal:
                    total_cal = x
                    
            elif age > 40:
                print("test")
                for Mk3,Mv3 in dicMCAL.get("40+").items():
                    print("test1")
                    if total_cal < x:
                        total_cal += Mv3
                if x > total_cal:
                    total_cal = x
                    print("test2")
            print(total_cal)

      
      
            if age>=1 and age<=15:
                print(age)
                if total_cal>0 and total_cal<=500:
                    self.label_16.setText(str(dicM['1-15']['RUNNING']))
                    print("M, 0-500")
                    time = 30

                elif total_cal>500 and total_cal<=760:
                    self.label_16.setText(str(dicM['1-15']['RUNNING'])+'\n'+str(dicM['1-15']['CYCLING']))
                    print("M, 500-760")
                    time = 40

                elif total_cal>760 and total_cal<=985:
                    self.label_16.setText(str(dicM['1-15']['RUNNING'])+'\n'+str(dicM['1-15']['CYCLING'])+'\n'+str(dicM['1-15']['DANCING']))
                    print("M, 760-985")
                    time = 70

                elif total_cal>985 and total_cal<=1097:
                    self.label_16.setText(str(dicM['1-15']['RUNNING'])+'\n'+str(dicM['1-15']['CYCLING'])+'\n'+
                                      str(dicM['1-15']['DANCING'])+'\n'+str(dicM['1-15']['BODYWEIGHT']))
                    print("M, 985-1097")
                    time = 100

                elif total_cal>1097 and total_cal<=1187:
                    self.label_16.setText(str(dicM['1-15']['RUNNING'])+'\n'+str(dicM['1-15']['CYCLING'])+'\n'+
                                      str(dicM['1-15']['DANCING'])+'\n'+str(dicM['1-15']['BODYWEIGHT'])+'\n'+
                                      str(dicM['1-15']['COOKING']))
                    time=130

                elif total_cal>1187:
                    self.label_16.setText(str(dicM['1-15']['RUNNING'])+'\n'+str(dicM['1-15']['CYCLING'])+'\n'+
                                      str(dicM['1-15']['DANCING'])+'\n'+str(dicM['1-15']['BODYWEIGHT'])+'\n'+
                                      str(dicM['1-15']['COOKING'])+'\n'+"Do It Again")
                    time="?"
            

            elif age>15 and age<=40:
                if total_cal>0 and total_cal<=450:
                    self.label_16.setText(str(dicM['16-40']['RUNNING']))
                    time = 30
                elif total_cal>450 and total_cal<=700:
                    self.label_16.setText(str(dicM['16-40']['RUNNING'])+'\n'+str(dicM['16-40']['CYCLING']))
                    time = 40
                    
                elif total_cal>700 and total_cal<=900:
                    self.label_16.setText(str(dicM['16-40']['RUNNING'])+'\n'+str(dicM['16-40']['CYCLING'])+'\n'+
                                      str(dicM['16-40']['DANCING']))
                    time=70
                elif total_cal>900 and total_cal<=1050:
                    self.label_16.setText(str(dicM['16-40']['RUNNING'])+'\n'+str(dicM['16-40']['CYCLING'])+'\n'+
                                      str(dicM['16-40']['DANCING'])+'\n'+str(dicM['16-40']['BODYWEIGHT']))
                    time=100
                elif total_cal>1050 and total_cal<=1380:
                    self.label_16.setText(str(dicM['16-40']['RUNNING'])+'\n'+str(dicM['16-40']['CYCLING'])+'\n'+
                                      str(dicM['16-40']['DANCING'])+'\n'+str(dicM['16-40']['BODYWEIGHT'])+'\n'+
                                      str(dicM['16-40']['COOKING']))
                    time=160
                elif total_cal>1380:
                    self.label_16.setText(str(dicM['16-40']['RUNNING'])+'\n'+str(dicM['16-40']['CYCLING'])+'\n'+
                                      str(dicM['16-40']['DANCING'])+'\n'+str(dicM['16-40']['BODYWEIGHT'])+'\n'+
                                      str(dicM['16-40']['GOLF'])+'\n'+"Do It Again")
                    time="?"
            elif age>40:
                if total_cal>0 and total_cal<=450:
                    print("rrrr")
                    self.label_16.setText(str(dicM['40+']['RUNNING']))
                    print("hhh")
                    time = 30
                elif total_cal>450 and total_cal<=700:
                    self.label_16.setText(str(dicM['40+']['RUNNING'])+'\n'+str(dicM['40+']['CYCLING']))
                    time = 40
                elif total_cal>700 and total_cal<=1210:
                    print("vvv")
                    self.label_16.setText(str(dicM['40+']['RUNNING'])+'\n'+str(dicM['40+']['CYCLING'])+'\n'+str(dicM['40+']['SWIMMING']))
                    print("fff")
                    time=100
                elif total_cal>1210 and total_cal<=1330:
                    self.label_16.setText(str(dicM['40+']['RUNNING'])+'\n'+str(dicM['40+']['CYCLING'])+'\n'+
                                      str(dicM['40+']['SWIMMING'])+'\n'+str(dicM['40+']['JOGGING']))
                    time=130
                elif total_cal>1330 and total_cal<=1660:
                    self.label_16.setText(str(dicM['40+']['RUNNING'])+'\n'+str(dicM['40+']['CYCLING'])+'\n'+
                                      str(dicM['40+']['SWIMMING'])+'\n'+str(dicM['40+']['JOGGING'])+'\n'+
                                      str(dicM['40+']['GOLF']))
                    time=190
                elif total_cal>1660:
                    print("ttt")
                    self.label_16.setText(str(dicM['40+']['RUNNING'])+'\n'+str(dicM['40+']['CYCLING'])+'\n'+
                                      str(dicM['40+']['SWIMMING'])+'\n'+str(dicM['40+']['JOGGING'])+'\n'+
                                      str(dicM['40+']['GOLF'])+'\n'+"Do It Again")
                    time="?"



###cal goal for female
        elif gender == "female":
            y = self.textEdit_5.toPlainText()
            y = int(y)
            total_cal_female = 0
            age = int(self.spinBox.value())
            age = int(age)
            print(age)
            if age > 1 and age <= 15:
                print("x")
                for Fk1,Fv1 in dicFCAL.get("1-15").items():
                    if total_cal_female < y:
                        total_cal_female += Fv1
                if y > total_cal_female:
                    total_cal_female=y
                    print("uu")
            elif age > 15 and age <= 40:
                for Fk2,Fv2 in dicFCAL.get("16-40").items():
                    if total_cal_female < y:
                        total_cal_female += Fv2
                if y > total_cal_female:
                    total_cal_female=y
            elif age > 40:
                print("test")
                for Fk3,Fv3 in dicFCAL.get("40+").items():
                    print("test1")
                    if total_cal_female < y:
                        total_cal_female += Fv3
                if y > total_cal_female:
                    total_cal_female = y
                    print("test2")
            print(total_cal_female)

            if age>=1 and age<=15 :
                print("yyy")
                print(total_cal_female)
                if total_cal_female>0 and total_cal_female<=450:
                    self.label_16.setText(str(dicF['1-15']['RUNNING']))
                    time = 30
                elif total_cal_female>450 and total_cal_female<=710:
                    self.label_16.setText(str(dicF['1-15']['RUNNING'])+'\n'+str(dicF['1-15']['CYCLING']))
                    time = 40
                elif total_cal_female>710 and total_cal_female<=960:
                    self.label_16.setText(str(dicF['1-15']['RUNNING'])+'\n'+str(dicF['1-15']['CYCLING'])+'\n'+
                                      str(dicF['1-15']['DANCING']))
                    time=70
                elif total_cal_female>960 and total_cal_female<=1060:
                    self.label_16.setText(str(dicF['1-15']['RUNNING'])+'\n'+str(dicF['1-15']['CYCLING'])+'\n'+
                                      str(dicF['1-15']['DANCING'])+'\n'+str(dicF['1-15']['BODYWEIGHT']))
                    time=100
                elif total_cal_female>1060 and total_cal_female<=1150:
                    print("yay")
                    self.label_16.setText(str(dicF['1-15']['RUNNING'])+'\n'+str(dicF['1-15']['CYCLING'])+'\n'+
                                      str(dicF['1-15']['DANCING'])+'\n'+str(dicF['1-15']['BODYWEIGHT'])+'\n'+
                                      str(dicF['1-15']['COOKING']))
                    time=130
                elif total_cal_female > 1150 :
                    print("y")
                    self.label_16.setText(str(dicF['1-15']['RUNNING'])+'\n'+str(dicF['1-15']['CYCLING'])+'\n'+
                                      str(dicF['1-15']['DANCING'])+'\n'+str(dicF['1-15']['BODYWEIGHT'])+'\n'+
                                      str(dicF['1-15']['COOKING'])+'\n'+"Do It Again")
                    time="?"

            elif age>15 and age<=40:
                if total_cal_female>0 and total_cal_female<=450:
                    self.label_16.setText(str(dicF['16-40']['RUNNING']))
                    time = 30
                elif total_cal_female>450 and total_cal_female<=690:
                    self.label_16.setText(str(dicF['16-40']['RUNNING'])+'\n'+str(dicF['16-40']['CYCLING']))
                    time = 40
                    print("A")
                elif total_cal_female>690 and total_cal_female<=890:
                    self.label_16.setText(str(dicF['16-40']['RUNNING'])+'\n'+str(dicF['16-40']['CYCLING'])+'\n'+
                                      str(dicF['16-40']['DANCING']))
                    time=70
                    print("B")
                elif total_cal_female>890 and total_cal_female<=1040:
                    self.label_16.setText(str(dicF['16-40']['RUNNING'])+'\n'+str(dicF['16-40']['CYCLING'])+'\n'+
                                      str(dicF['16-40']['DANCING'])+'\n'+str(dicF['16-40']['BODYWEIGHT']))
                    time=100
                elif total_cal_female>1040 and total_cal_female<=1360:
                    self.label_16.setText(str(dicF['16-40']['RUNNING'])+'\n'+str(dicF['16-40']['CYCLING'])+'\n'+
                                      str(dicF['16-40']['DANCING'])+'\n'+str(dicF['16-40']['BODYWEIGHT'])+'\n'+
                                      str(dicF['16-40']['COOKING']))
                    time=160
                elif total_cal_female>1360:
                    self.label_16.setText(str(dicF['16-40']['RUNNING'])+'\n'+str(dicF['16-40']['CYCLING'])+'\n'+
                                      str(dicF['16-40']['DANCING'])+'\n'+str(dicF['16-40']['BODYWEIGHT'])+'\n'+
                                      str(dicF['16-40']['GOLF'])+'\n'+"Do It Again")
                    time="?"
            
            elif age>40:
                if total_cal_female>0 and total_cal_female<=450:
                    self.label_16.setText(str(dicF['40+']['RUNNING']))
                    time = 30
                elif total_cal_female>450 and total_cal_female<=700:
                    self.label_16.setText(str(dicF['40+']['RUNNING'])+'\n'+str(dicF['40+']['CYCLING']))
                    time = 40
                elif total_cal_female>700and total_cal_female<=1110:
                    print("ooo")
                    self.label_16.setText(str(dicF['40+']['RUNNING'])+'\n'+str(dicF['40+']['CYCLING'])+'\n'+
                                      str(dicF['40+']['SWIMMING']))
                    print("kkk")
                    time=100
                elif total_cal_female>1110 and total_cal_female<=1220:
                    self.label_16.setText(str(dicF['40+']['RUNNING'])+'\n'+str(dicF['40+']['CYCLING'])+'\n'+
                                      str(dicF['40+']['SWIMMING'])+'\n'+str(dicF['40+']['JOGGING']))
                    time=130
                elif total_cal_female>1220 and total_cal_female<=1550:
                    self.label_16.setText(str(dicF['40+']['RUNNING'])+'\n'+str(dicF['40+']['CYCLING'])+'\n'+
                                      str(dicF['40+']['SWIMMING'])+'\n'+str(dicF['40+']['JOGGING'])+'\n'+
                                      str(dicF['40+']['GOLF']))
                    time=190
                elif total_cal_female>1550:
                    self.label_16.setText(str(dicF['40+']['RUNNING'])+'\n'+str(dicF['40+']['CYCLING'])+'\n'+
                                      str(dicF['40+']['SWIMMING'])+'\n'+str(dicF['40+']['JOGGING'])+'\n'+
                                      str(dicF['40+']['GOLF'])+'\n'+"Do It Again")
                    time="?"

        name=self.textEdit.toPlainText()
        
        age=self.spinBox.value()
      
        cal=self.textEdit_5.toPlainText()
        
        self.label_11.setText("Hello!"+" "+str(name)+" "+"Gender:"+" "+str(gender)+" "+"Age:"+str(age)+" "+"Calories Burn Goal:"+str(cal)+".")
        
        self.label_18.setText(str(time))
        
                
### output page
    def gopage3(self):
        self.stackedWidget.setCurrentIndex(1)
    def backtopage2(self):
        self.stackedWidget.setCurrentIndex(0)
### thank you page
    def gopage4(self):
        self.stackedWidget.setCurrentIndex(2)

    def closewindow(self):
        os.system(cmd)
        self.Qtcore.QCoreApplication.instance().quit()
        

    def retranslateUi(self, PhomGubThank):
        _translate = QtCore.QCoreApplication.translate
        PhomGubThank.setWindowTitle(_translate("PhomGubThank", "My Baby"))
        self.label_4.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#c95dd8;\">Personal Information</span></p></body></html>"))
        self.pushButton.setText(_translate("PhomGubThank", "OK"))
        self.label_2.setText(_translate("PhomGubThank", "Name:"))
        self.label_5.setText(_translate("PhomGubThank", "Age:"))
        self.label_6.setText(_translate("PhomGubThank", "Weight(Kg):"))
        self.label_7.setText(_translate("PhomGubThank", "Height(m):"))
        self.label_8.setText(_translate("PhomGubThank", " Calories Burn Goal Per Day:"))
        self.pushButton_2.setText(_translate("PhomGubThank", "CANCEL"))
        self.pushButton_8.setText(_translate("PhomGubThank", "CALCULATE BMI"))
        self.radioButton.setText(_translate("PhomGubThank", "MALE"))
        self.radioButton_2.setText(_translate("PhomGubThank", "FEMALE"))
        self.label_14.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Follow This Program!</span></p></body></html>"))
        self.pushButton_5.setText(_translate("PhomGubThank", "NEXT"))
        self.pushButton_6.setText(_translate("PhomGubThank", "BACK"))
        self.label_9.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">BMI:</span></p></body></html>"))
        self.label_15.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\"><br/></span></p></body></html>"))
        self.label_17.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Total Time:</span></p></body></html>"))
        self.label_18.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\"><br/></span></p></body></html>"))
        self.pushButton_3.setText(_translate("PhomGubThank", "EXIT"))
        self.label_10.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" color:#800080;\">THANK YOU!</span></p><p align=\"center\"><span style=\" color:#fd8008;\">STAY HEALTHY</span><span style=\" color:#fc02ff;\">&lt;3</span></p></body></html>"))
        self.label_3.setText(_translate("PhomGubThank", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#fd1e4f;\">Slim W</span><span style=\" font-size:36pt; font-weight:600; color:#ff3f45;\">i</span><span style=\" font-size:36pt; font-weight:600; color:#ff0071;\">th Thanky</span></p><p align=\"center\"><span style=\" font-size:36pt; color:#ff3f45;\"><br/></span></p></body></html>"))
        self.label_12.setText(_translate("PhomGubThank", "<html><head/><body><p>Workout is our favorite</p></body></html>"))
        self.pushButton_7.setText(_translate("PhomGubThank", "LET SLIM"))
        self.toolBar.setWindowTitle(_translate("PhomGubThank", "toolBar"))

if __name__ == "__main__" :
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhomGubThank = QtWidgets.QMainWindow()
    ui = Ui_PhomGubThank()
    ui.setupUi(PhomGubThank)
    PhomGubThank.show()
    sys.exit(app.exec_())
